# Generated by Django 5.0.3 on 2024-07-11 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_car_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.driver'),
        ),
    ]
