# Generated by Django 5.0.3 on 2024-07-11 13:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_car_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('date_issued', models.DateField(default=django.utils.timezone.now)),
                ('fuel_consumption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fuelconsumption')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.payment')),
            ],
        ),
    ]
