# Generated by Django 5.0.3 on 2024-07-13 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='fuel_consumption',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.fuelconsumption'),
            preserve_default=False,
        ),
    ]
