# Generated by Django 5.0.3 on 2024-07-16 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_payment_fuel_consumption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='fuel_consumption',
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_date', models.DateField()),
                ('fuel_advance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_advance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('truck_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('varriance_in_fuel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deduction_proof', models.ImageField(upload_to='proof/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.car')),
                ('car_ownership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carownership')),
            ],
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
