# Generated by Django 5.0.3 on 2024-07-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_payment_fuel_consumption_deduction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deduction',
            name='deduction_proof',
            field=models.FileField(upload_to='proof/'),
        ),
    ]
