# Generated by Django 5.0.3 on 2024-07-17 04:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_deduction_deduction_proof'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='amount_per_day',
        ),
        migrations.RemoveField(
            model_name='car',
            name='make',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='invoice_details',
        ),
        migrations.RemoveField(
            model_name='productdelivery',
            name='product_name',
        ),
        migrations.AddField(
            model_name='car',
            name='chassis_number',
            field=models.CharField(default=222345, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuelconsumption',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='Owner_ids',
            field=models.DecimalField(decimal_places=2, default=1234567890, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='car',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.car'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='car_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='delivery_dates',
            field=models.ManyToManyField(to='core.productdelivery'),
        ),
        migrations.AddField(
            model_name='payment',
            name='extra_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, editable=False, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productdelivery',
            name='car_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productdelivery',
            name='delivery_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='productdelivery',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=1234, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productdelivery',
            name='product_category',
            field=models.CharField(choices=[('seed', 'Seed'), ('fertilizer', 'Fertilizer'), ('non_agriculture', 'Non-Agriculture')], default='seed', max_length=20),
        ),
        migrations.AddField(
            model_name='productdelivery',
            name='tms',
            field=models.FileField(default=12, upload_to='tms/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productdelivery',
            name='truck_number',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('mazutu', 'Mazutu'), ('essense', 'Essense')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(choices=[('Fuso L.C', 'Fuso L.C'), ('Fuso Ben', 'Fuso Ben'), ('Daihatsu', 'Daihatsu'), ('Pick-up', 'Pick-up'), ('Actros', 'Actros')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('momo', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque')], max_length=20),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('full_paid', 'Full Paid'), ('partial_paid', 'Partial Paid')], max_length=20)),
                ('remaining_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('momo', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque')], max_length=20)),
                ('fuel_advance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cash_advance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('truck_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('variance_in_fuel', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.car')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.driver')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.owner')),
                ('product_delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productdelivery')),
            ],
        ),
    ]
